a = input('Digite algo: ')
print('O tipo primitivo desta palavra é: ', type(a))
print('Só tem espaços? : ', a.isspace())
print('é um número? : ', a.isnumeric())
print('é alfabético? : ', a.isalpha())
print('É alfanumérico? : ', a.isalnum())
print('Está em maiúsculas? : ', a.isupper())
print('Está em minúsculas? : ', a.islower())
print('Está capitalizada?', a.istitle())
